# Generated by Django 2.2.7 on 2019-12-06 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0003_patientdetails_age'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patientdetails',
            options={'verbose_name_plural': 'Patient Details'},
        ),
        migrations.AlterModelOptions(
            name='patientmedicalrecords',
            options={'verbose_name_plural': 'Patient Medical Records'},
        ),
        migrations.RemoveField(
            model_name='patientmedicalrecords',
            name='follow_up_date',
        ),
        migrations.RemoveField(
            model_name='patientmedicalrecords',
            name='visit_date',
        ),
        migrations.AlterField(
            model_name='patientmedicalrecords',
            name='patient_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_records.PatientDetails'),
        ),
        migrations.AlterField(
            model_name='patientpayment',
            name='patient_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_records.PatientDetails'),
        ),
        migrations.CreateModel(
            name='PatientSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField(auto_now_add=True)),
                ('session_starting_time', models.TimeField(auto_now_add=True)),
                ('session_ending_time', models.TimeField(auto_now=True)),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('doctor_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_records.PatientMedicalRecords')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient_records.PatientDetails')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_records.PatientPayment')),
            ],
            options={
                'verbose_name_plural': 'Sessions',
            },
        ),
    ]
