# Generated by Django 2.2.7 on 2019-12-06 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0004_auto_20191206_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsession',
            name='session_state',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsession',
            name='session_ending_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
