# Generated by Django 2.2.7 on 2019-12-10 06:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0005_auto_20191206_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientpayment',
            name='patient_details',
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='company_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patientpayment',
            name='payment_by',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='patientsession',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_records.PatientPayment'),
        ),
    ]
