# Generated by Django 2.2.7 on 2019-12-10 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0006_auto_20191210_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsession',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patient_records.PatientPayment'),
        ),
    ]
