# Generated by Django 2.2.7 on 2019-12-10 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0007_auto_20191210_0658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientpayment',
            old_name='payment_by',
            new_name='payment_mode',
        ),
    ]
