# Generated by Django 2.2.7 on 2019-12-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_records', '0008_auto_20191210_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientmedicalrecords',
            name='patient_details',
        ),
        migrations.AlterField(
            model_name='patientmedicalrecords',
            name='complaints',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalrecords',
            name='investigations',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='patientmedicalrecords',
            name='treatment',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='patientsession',
            name='session_ending_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
